### ISSUE TITLE
add Maven instruction To build project

### ISSUE THREAD

**Issue by madeindjs** [RohitAwate/Everest#2]
Is it possible to add Maven instruction To build project on readme?

**Comment by RohitAwate** [comment]
Sure I'll add it in the next update.

For now:
- Make sure you have Java 8 to build and run Everest.
- Just `cd` into the folder and build the project with:
`mvn clean package`
- An executable JAR file will be generated in the `target` directory:
`cd target`
- To run the executable:
`java -jar Everest-Alpha-1.0.jar`

I hope this helped, I'll close the issue. :)

**Comment by madeindjs** [comment]
Great, thank you for your work!
