### ISSUE TITLE
Development freeze?

### ISSUE THREAD

**Issue by renannprado** [RohitAwate/Everest#33]
I came to know about this project through reddit, but after a long time only now I had the time to try it out. :)
Nice job btw!
I don't currently know if Everest is having any kind of limitation, but I do believe that there are features planned, but not implemented. I see that the development stopped for couple of months already so I'd like to understand what's the plan for the project in general? I believe you still want to keep development of it.
Or if the project is abandoned, that's also fine. I really like the project, so **maybe** if I have the time I would like to help :)

**Comment by renannprado** [comment]
hey @RohitAwate

**Comment by RohitAwate** [comment]
Hi @renannprado, thank you for your interest in Everest! :)

The development hasn't really stopped, but I'm not making it a priority. I'm extremely busy right now with university stuff and also trying to focus on learning new things. Plus, the OAuth 2.0 logic has gotten quite complex and the decoupling of JavaFX from the JDK has made builds and distribution quite tedious. This puts me off every time I feel like working on Everest. I plan to continue working on every now and then, no promises though. :(

Apologies if this is extremely vague, but so are my thoughts at the moment. Feel free to hack away  and merge a PR if you have time.

Here are some ideas that I'd really appreciate some help with (I'm unable to figure these out for the life of me):
- set up the build with **just Maven**, no extra crap
- set up the CI build to upload platform-specific installers to GitHub Releases. (both tagged and running releases)

Closing this.
Thanks again, have a good one! :)

**Comment by renannprado** [comment]
@RohitAwate I'll spend some time to see if I can get the build with maven (+jlink) working just fine. Let's see if I'm able to provide something over this weekend :)

**Comment by renannprado** [comment]
@RohitAwate I have spend a lot of time on this. 
I've even patched some dependencies with `module-info.java` files, but it seems to me now that the only issue left is the jersey dependencies.
I'll spend some time to see if I can remove the jersey dependencies (maybe use the standard java HTTP client, just as a test).

**Comment by RohitAwate** [comment]
@renannprado Sounds great! I've been planning to get rid of the Jersey dependencies and switch to the Java 11 HTTP client. Feel free to do that if you're interested and have the time, otherwise I'll be doing that anyway.

Looking forward to your PR. Thanks a lot! :)

**Comment by renannprado** [comment]
@RohitAwate in a very hacky way (just deleting code, basically), I was able to remove the jersey and richtextfx just to test my theory.
After that I was able to use jlink successfully. however now I face the following exception: 

```
Caused by: java.lang.IllegalAccessError: class com.jfoenix.skins.JFXProgressBarSkin (in module com.jfoenix) cannot access class com.sun.javafx.scene.NodeHelper (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.scene to module com.jfoenix
```

Yeah... that's not good news. Well, I'm not jigsaw expert, but it seems nearly impossible to build the project with jlink with the dependencies the project has. Most of them seem not to be prepared for jigsaw at all and looking up for issues in github it doesn't seem that they really attempted to address the issue. I don't know why, because jigsaw + javafx is perfect for distribution.

To be honest, as much as it sucks, I'd just remove all problematic dependencies (not sure how difficult 'cause I'm not a javafx expert either) if it was my call.
The other option would be to maintain patched versions of those with the `module-info.java`, this might not be difficult actually. I'll think I'll try to checkout `JFoenix` and add the module file to see how it goes.

Looks like you have to be picky with dependencies when you want to build with jlink :disappointed: . It feels like jigsaw was released, but there not much information on how to get it right.

**Edit:**

My bad, JFoenix has a version with the `module-info.java`, which now makes things even more weird.

**Comment by renannprado** [comment]
I'll just leave few references that helped in my journey so far:

https://github.com/codetojoy/easter_eggs_for_java_9/
https://github.com/openjfx/samples

The `samples` repository contains a javafx project fully working with jlink. But of course, it doesn't depend on anything other than javafx.

**Comment by RohitAwate** [comment]
Wow it's gonna be tricky. I wouldn't mind getting rid of JFoenix (not using it in a lot of places and easy to switch to the standard JavaFX controls) but RichTextFX is gonna be hard since it's a quite sophisticated and mature component. I've got my exams on right now, but I'll check out your links once I'm free.

Thanks for your efforts! :)
