### ISSUE TITLE
Application does not run on Mac OSX

### ISSUE THREAD

**Issue by btbytes** [RohitAwate/Everest#7]
* Mac OS 10.12.6
* Java `OpenJDK Runtime Environment (Zulu 8.23.0.3-macosx) (build 1.8.0_144-b01)`

```
$ java -jar Everest-Alpha-1.0.jar
Error: Could not find or load main class com.rohitawate.everest.main.Main
```

**Comment by jessechahal** [comment]
The title isn't true, I just ran on latest MacOS 
- MacOS 10.13.4
- java -version 
```
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```
Below is output of running it

```
java -jar ~/Downloads/Everest-Alpha-1.0.jar
Connected to database.
Settings file found. Loading settings...
Settings file not found. Using defaults
Application state file not found. Loading default state.
May 03, 2018 7:26:46 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.141 by JavaFX runtime of version 8.0.121
```
Maybe OpenJDK doesn't ship support for JavaFX or some related libraries? Try using the oracleJDK.

**Comment by RohitAwate** [comment]
@jessechahal is right. You'll need to install OpenJFX if you're going to stick to OpenJDK, since JavaFX doesn't come with it or you could just use Oracle's JDK 8.
