### ISSUE TITLE
Can't set custom Content-Type

### ISSUE THREAD

**Issue by virmundi** [RohitAwate/Everest#9]
I use custom mimetypes for all of my calls. When attempting to post, the header value I put in gets overridden by the body configuration. I've not been able to undo that override.

**Comment by RohitAwate** [comment]
I see. Yes, Everest determines the content type from the body.
I'll add a mechanism by which the content type from the headers (if any) overrides the one determined from the body. This will probably take a couple of weeks though. I have my finals coming up and I'm also working on the core-optimization branch. Sound good?

**Comment by RohitAwate** [comment]
Hi,

I've been evaluating this issue and have a few questions. To be frank, I've never used custom types so I tried them on Insomnia and noticed that it allows overriding for all types of request bodies except multipart/form-data. Do you happen to know why they're doing so?

I have a solution almost ready. Feel free to contribute though. I'll be putting up a Contributions Guide soon so I suggest you wait for that before making a PR.

**Comment by RohitAwate** [comment]
Not preachy at all, that's really helpful. Thanks a lot! :+1: 

I've made changes to DataDispatchRequestManager, which handles POST, PUT and PATCH requests. Basically, it will still determine the content type from the UI (based on the tab you have selected), but it will now check for an override before making the request.

I request you to try out this [this](https://github.com/RohitAwate/Everest/files/1977357/Everest-Alpha-1.0-TestBuild.zip) test build and let me know if this works for you. If you have any issues, we'll sort them out else I'll push the changes to the _core-optimization_ branch. I have a few more things in mind before I push out Alpha 1.1 so I suggest you build from _core-optimization_ meanwhile.

**Comment by virmundi** [comment]
That worked great.
